on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: breastcancer.azurecr.io
        username: ${{ secrets.acr_breastcancer_username }}
        password: ${{ secrets.acr_breastcancer_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t breastcancer.azurecr.io/breastcancerkubernetescluster:${{ github.sha }}
        docker push breastcancer.azurecr.io/breastcancerkubernetescluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_breastcancerkubernetescluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep breast-cancer-kubernetes-cluster8aeb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace breast-cancer-kubernetes-cluster8aeb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: breast-cancer-kubernetes-cluster8aeb
        container-registry-url: breastcancer.azurecr.io
        container-registry-username: ${{ secrets.acr_breastcancer_username }}
        container-registry-password: ${{ secrets.acr_breastcancer_password }}
        secret-name: breastcancerdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: breast-cancer-kubernetes-cluster8aeb
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          breastcancer.azurecr.io/breastcancerkubernetescluster:${{ github.sha }}
        imagepullsecrets: |
          breastcancerdockerauth